name = "My Webring"
domain = "ring.example.org"
description = ["Welcome to my fantastic webring!", "It has all my friends' websites and mine!"]
join_the_ring_path = "join_ring.html"
legal_information_path = "legal_information.html"
favicon_path = "logo.png"

[translation]
  random_website = "Go to a random website"
  internal_pages = "Internal pages:"
  home_page = "home"
  join_the_ring_page = "join the ring"
  legal_information_page = "legal information"

[[website]]
  name = "Example"
  url = "https://example.org/"
[[website]]
  name = "Anhgelus Morhtuuzh"
  url = "https://anhgelus.world/"
